bootstrap.peg.go, peg.peg
Lots of example PEG grammars use this unicode arrow. Allowing it is a nicety.
=> Allow ← for LeftArrow

bootstrap.peg.go, peg.go
In translatePositions(), the indexes in the `positions` slice are
rune indexes, not byte counts. However, when looping over `buffer[0:]`
the counter `i` will be a byte count so that when multibyte characters
are used,
- some rune indexes in the `positions` slice will never be matched in
the inner loops
- line/symbol pairs will not match the correct numbers after a multi-
byte character.
Looping over a rune slice fixes this issue.
=> when computing line/symbol pairs, loop over rune array instead of string

peg.go
Fix error "_buffer declared and not used" if HasPush is false when running peg.
=> Fix: _buffer declared and not used

README.md, bootstrap.peg.go, peg.go
These commits fixes golint warnings I got for the code generated by peg. Closes #48.
Before: 
```
configfile.peg.go:10:7: don't use underscores in Go names; const end_symbol should be endSymbol
configfile.peg.go:29:2: don't use underscores in Go names; const rule_ should be rule
configfile.peg.go:38:2: don't use underscores in Go names; const rulePre_ should be rulePre
configfile.peg.go:39:2: don't use underscores in Go names; const rule_In_ should be ruleIn
configfile.peg.go:40:2: don't use underscores in Go names; const rule_Suf should be ruleSuf
configfile.peg.go:101:1: receiver name ast should be consistent with previous receiver name node for node32
configfile.peg.go:210:10: should omit 2nd value from range; this loop is equivalent to `for i := range ...`
configfile.peg.go:349:9: …
```
=> Fix golint warnings in generated code

Makefile, bootstrap.peg.go, bootstrap/main.go, main.go, peg.go, peg_test.go
Implements #53 and improve #51.
Didn`t dare to check if peg itself could be made with such option. 
As per #51 benchcmp for extremely stupid grammar with actions (see at https://github.com/egorse/peg_ex)
```
benchmark           old ns/op     new ns/op     delta
Benchmark100-4      98626         6583          -93.33%
Benchmark200-4      106745        11241         -89.47%
Benchmark500-4      125213        25230         -79.85%
Benchmark1k-4       154281        50276         -67.41%
Benchmark10k-4      689338        482092        -30.06%
Benchmark20k-4      678916        483708        -28.75%
Benchmark50k-4      3255189       2337557       -28.19%
Benchmark100k-4     6744704       4654680       -30.99%
Benchmark200k-4     14254404      9987951       -29.93%
Benchmark500k-4     36308161 …
```
=> New option -noast to generate parser w/out AST support

bootstrap.peg.go, peg.go
More important (to me, at least) for dumb terminals / frontends where
escape codes don't work (i.e., automated builds and so on that have
test output dropped into a browser as preformatted text). Aside from
that, it'd be nice to have printing respect the Peg config in use.
To avoid breaking existing calls to Print and PrintSyntaxTree, new
forms of those methods with Pretty prefixed to them have been added
along with a *node32.print method that accepts a pretty flag to switch
between format strings.  This at least allows existing use of the Print
functions to work, even if it'll stop colorizing their output with
escapes unless Pretty is true in the Peg struct.
Includes a regenerated bootstrap.peg.go so tests pass.
=> Make Peg.PrintSyntaxTree respect Pretty flag

peg.go
The switch -noast cause text variable being declared even if there is no capture exists.
This small patch fixes it.
=> Fixed unused variable where there is no string capture.

grammars/c/c.peg, grammars/c/grammar_test.go
This is the pull request for https://github.com/pointlander/peg/issues/66:
- Integrates the new approach of the recursive CastExpression grammar, which ended up being the only approach that worked across a wide variety of C styles.
- Includes a unit test for the grammar's base function.
=> Peg 66 pull

bootstrap/main.go, main.go, peg.go
to support `go generate`
Signed-off-by: Alejandro Mery <amery@geeks.cl>
=> Add //go:generate to the output

grammars/c/Makefile, grammars/c/c.peg, grammars/c/grammar_test.go
Bring in the ability to compile "common" (not "standard") C code by expanding the acceptable grammar to include common compiler extensions. This is the first part; "simple" changes that do not introduce any new keywords.
=> Peg 67 pull of "simple" changes

main.go, peg.go, peg_test.go
Forces peg to non-zero exit if compilation generates any warnings.
Useful for bailing out of make
=> strict mode flag

Makefile, grammars/c/grammar_test.go, grammars/c/main.go, grammars/java/main.go, peg.peg.go, tree/peg.go
gofmt expects alphabetized imports, so sort the import list. Also
includes a 'fmt' makefile rule to check the code against gofmt.
=> alphabetically emit imports and check for gofmt violations

tree/peg.go
Adds a method to generated parsers called `WriteSyntaxTree` that accepts an `io.Writer` the caller supplies. Really handy for logging the AST from a parse.
Thank you for the library!
=> add WriteSyntaxTree to generated parser API

peg.peg.go, tree/peg.go
When print syntax tree functions are used with an io.Writer, indentation is broken because of a typo that is fixed in this PR
=> fix indentation for syntax tree io.Writer output

peg.peg, peg.peg.go
Go package imports can contain digits. In the present implementation any such import is rejected as a parsing error. I simply added `0-9` to the allowable characters for an ImportName to fix this.
The astute may note that my own profile name contains a digit, and therefore without this change none of my own packages can be imported into a grammar file.
Seriously though smallest change ever, all tests are still passed, and I can't think of any way this could cause any sort of problem.
=> Allow digits in imported package names

grammars/c/c.peg, grammars/c/c_test.go
Fixes https://github.com/pointlander/peg/issues/121 (c.peg cannot parse wide-string literals).
The issue appears to be that the `L` prefix will be captured by the `Identifier` subrule in `PrimaryExpression` before `StringLiteral` can capture it.  My fix is to reorder these subrules, putting `StringLiteral` before `Identifier`.
=> fix c grammar for wide string literals

peg.peg.go, tree/peg.go
The result with the -switch option includes not only the decision based on the case, but also the duplication of "if" blocks that make the same result.
In this PR, I removed this unnecessary if-block.
=> Remove unnecessary "if" block

tree/peg.go
When using peg via `go run` the executable name is a path that changes every invocation. This PR hardcodes the first argument to `peg` so that subsequent runs of `go run` always generate the same output file.
Before
```
// Code generated by /var/folders/w2/fb613tqx6rzftr9k0v_pcfmr0000gn/T/go-build1383365192/b001/exe/peg grammar.peg DO NOT EDIT.
```
After
```
// Code generated by peg grammar.peg DO NOT EDIT.
```
=> Make executable name static in generated code

README.md
* Looks like GitHub user github.com/robmuh is now known as github.com/rwxrob but the dtime repository is no longer among his public repositories.
=> Remove broken link to GitHub project

tree/peg.go
* extract functions to methods
* isolate recursive functions
* use separate declaration statements in new lines for variables
=> Refactor tree implementation
